variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: normal
  NODE_OPTIONS: --no-warnings
stages:
  - test

tests:
  stage: test
  tags:
    - windows
  before_script:
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install -y yarn
    - refreshenv
  script:
    - yarn
    - yarn jest --testTimeout 30000
